/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SongBuilderRouteImport } from './routes/song-builder'
import { Route as IndexRouteImport } from './routes/index'

const SongBuilderRoute = SongBuilderRouteImport.update({
  id: '/song-builder',
  path: '/song-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/song-builder': typeof SongBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/song-builder': typeof SongBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/song-builder': typeof SongBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/song-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/song-builder'
  id: '__root__' | '/' | '/song-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SongBuilderRoute: typeof SongBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/song-builder': {
      id: '/song-builder'
      path: '/song-builder'
      fullPath: '/song-builder'
      preLoaderRoute: typeof SongBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SongBuilderRoute: SongBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
